// supabase config
const SUPABASE_URL = "https://roezubhntsugznbbekdk.supabase.co";
const SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvZXp1YmhudHN1Z3puYmJla2RrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA3MzgwNTAsImV4cCI6MjA4NjMxNDA1MH0.lVyM8spmQk3zQ69TrumVdVQKv9lRJNDpI5eRKT45yIU";

