var PRICE_LIST = [
    { category: "Micro Controller", name: "Arduino Uno R3 (smd)", buying_price: 400, selling_price: 480 },
    { category: "Micro Controller", name: "Arduino uno R3", buying_price: 500, selling_price: 0 },
    { category: "Micro Controller", name: "Arduino Nano (micro USB)", buying_price: 320, selling_price: 380 },
    { category: "Micro Controller", name: "Arduino Nano (Type C)", buying_price: 0, selling_price: 0 },
    { category: "Micro Controller", name: "Arduino Mega", buying_price: 1300, selling_price: 1650 },
    { category: "Micro Controller", name: "ESP32 Dev kit C (Type C Version)", buying_price: 380, selling_price: 500 },
    { category: "Micro Controller", name: "ESP32 Dev Kit V1 (Micro USB Version)", buying_price: 350, selling_price: 450 },
    { category: "Motor", name: "TT motor 6V", buying_price: 60, selling_price: 80 },
    { category: "Motor", name: "TT motor Wheel", buying_price: 50, selling_price: 70 },
    { category: "Motor", name: "BLDC Motor", buying_price: 0, selling_price: 0 },
    { category: "Motor", name: "37GB 400 rpm", buying_price: 780, selling_price: 1300 },
    { category: "Motor", name: "37G 350rpm", buying_price: 800, selling_price: 1300 },
    { category: "Motor", name: "300rpm 12V Motor", buying_price: 0, selling_price: 0 },
    { category: "Motor", name: "500rpm 12V Motor", buying_price: 0, selling_price: 0 },
    { category: "Motor", name: "16GA 600rpm 6V Motor(JGA16-050)", buying_price: 320, selling_price: 400 },
    { category: "Motor", name: "25GA 600rpm 12V Motor", buying_price: 380, selling_price: 500 },
    { category: "Motor", name: "Servo Motor (MG-995 - 180)", buying_price: 250, selling_price: 350 },
    { category: "Motor", name: "Servo Motor (MG-996 - 360)", buying_price: 250, selling_price: 250 },
    { category: "Motor", name: "MG90", buying_price: 0, selling_price: 200 },
    { category: "Motor", name: "Servo Motor (SG-90)", buying_price: 0, selling_price: 0 },
    { category: "Motor", name: "Centrifugal Pump", buying_price: 200, selling_price: 240 },
    { category: "Motor", name: "12V Air pump", buying_price: 450, selling_price: 515 },
    { category: "Motor", name: "6V Water Pump", buying_price: 50, selling_price: 75 },
    { category: "Motor Mountings", name: "Coupler (4mm Hex)", buying_price: 80, selling_price: 100 },
    { category: "Motor Mountings", name: "Coupler (6mm Hex)", buying_price: 80, selling_price: 145 },
    { category: "Motor Mountings", name: "L Clamp (37GB)", buying_price: 110, selling_price: 170.2 },
    { category: "Motor Mountings", name: "L Clamp (25GA)", buying_price: 80, selling_price: 100 },
    { category: "Wheel", name: "N20 wheel", buying_price: 55, selling_price: 70 },
    { category: "Wheel", name: "Ball Caster", buying_price: 60, selling_price: 70 },
    { category: "Wheel", name: "65mm Wheel", buying_price: 150, selling_price: 215 },
    { category: "Fan", name: "Exhaust Fan 2in", buying_price: 45, selling_price: 100 },
    { category: "Fan", name: "Exhaust Fan 3 in", buying_price: 70, selling_price: 70 },
    { category: "Motor Driver", name: "L293D Motor Driver", buying_price: 130, selling_price: 160 },
    { category: "Motor Driver", name: "L298 Motor Driver", buying_price: 120, selling_price: 140 },
    { category: "Motor Driver", name: "ESC40A", buying_price: 0, selling_price: 720 },
    { category: "Motor Driver", name: "BTS7960(IBT2) Motor Driver", buying_price: 360, selling_price: 540 },
    { category: "Sensor", name: "Sonar Sensor", buying_price: 60, selling_price: 70 },
    { category: "Sensor", name: "35mm Piezo discs", buying_price: 20, selling_price: 35 },
    { category: "Sensor", name: "pH sensor", buying_price: 1950, selling_price: 1950 },
    { category: "Sensor", name: "Vibration Sensor", buying_price: 0, selling_price: 0 },
    { category: "Sensor", name: "IR sensor with emmiter (TCRT-5000)", buying_price: 13, selling_price: 15 },
    { category: "Sensor", name: "IR Sensor", buying_price: 35, selling_price: 35 },
    { category: "Sensor", name: "RTC", buying_price: 0, selling_price: 0 },
    { category: "Sensor", name: "Soil temperature Sensor", buying_price: 0, selling_price: 0 },
    { category: "Sensor", name: "Soil Sensor Moisture Sensor", buying_price: 70, selling_price: 90 },
    { category: "Sensor", name: "Temperature sensor(LM-35)", buying_price: 50, selling_price: 100 },
    { category: "Sensor", name: "Humidity sensor", buying_price: 0, selling_price: 0 },
    { category: "Sensor", name: "Flame Sensor (3pin)", buying_price: 35, selling_price: 60 },
    { category: "Sensor", name: "Gyroscope (MPU-6050)", buying_price: 180, selling_price: 230 },
    { category: "Wires", name: "Female To Female Jumper Wire", buying_price: 1.5, selling_price: 2 },
    { category: "Wires", name: "Femlae To Male Jumper Wire", buying_price: 1.5, selling_price: 2 },
    { category: "Wires", name: "Male to Male Jumper Wire", buying_price: 1.5, selling_price: 2 },
    { category: "Wires", name: "Normal Wires 22 gauge Per feet", buying_price: 5, selling_price: 15 },
    { category: "Buck", name: "Step Up Buck Converter", buying_price: 60, selling_price: 70 },
    { category: "Buck", name: "Step down 360buck", buying_price: 45, selling_price: 60 },
    { category: "Buck", name: "Step Down Buck (LM2596)", buying_price: 50, selling_price: 70 },
    { category: "Coms", name: "HC-05", buying_price: 230, selling_price: 300 },
    { category: "Coms", name: "FlySky", buying_price: 0, selling_price: 0 },
    { category: "display", name: "LCD Calculator Display", buying_price: 120, selling_price: 200 },
    { category: "display", name: "OLED 1.3in", buying_price: 350, selling_price: 470 },
    { category: "display", name: "OLED 0.93in", buying_price: 180, selling_price: 230 },
    { category: "Input", name: "Push Button 2pin", buying_price: 3, selling_price: 4 },
    { category: "Input", name: "Push Button 4pin small", buying_price: 3, selling_price: 4 },
    { category: "Input", name: "Push Button 4 pin Big", buying_price: 5, selling_price: 7 },
    { category: "Input", name: "Toggle Switch", buying_price: 25, selling_price: 50 },
    { category: "Input", name: "Rotary Encoder", buying_price: 75, selling_price: 100 },
    { category: "Input", name: "Potentiometers", buying_price: 10, selling_price: 15 },
    { category: "Input", name: "Mux module 8 channle", buying_price: 150, selling_price: 180 },
    { category: "Input", name: "4*4 keypad", buying_price: 60, selling_price: 60 },
    { category: "Input", name: "Mux module 16 channle", buying_price: 0, selling_price: 0 },
    { category: "Input", name: "Switch Big", buying_price: 10, selling_price: 15 },
    { category: "Input", name: "Switch", buying_price: 5, selling_price: 15 },
    { category: "Tools", name: "Screw sets", buying_price: 120, selling_price: 170 },
    { category: "Tools", name: "Screw Sets(Green", buying_price: 150, selling_price: 200 },
    { category: "Tools", name: "7\" Wire Stripper", buying_price: 170, selling_price: 245 },
    { category: "Tools", name: "Hot Glue Gun", buying_price: 200, selling_price: 250 },
    { category: "Tools", name: "Glue Stick", buying_price: 12, selling_price: 15 },
    { category: "Tools", name: "Soldering Iron (908)", buying_price: 240, selling_price: 360 },
    { category: "Tools", name: "Soldering Iron (HI Loo)", buying_price: 240, selling_price: 360 },
    { category: "Tools", name: "Soldering Lead Cat", buying_price: 240, selling_price: 320 },
    { category: "Tools", name: "Soldering Lead Sigma", buying_price: 80, selling_price: 115 },
    { category: "Tools", name: "Soldering iron stand", buying_price: 60, selling_price: 100 },
    { category: "Tools", name: "tip cleaner Foam", buying_price: 20, selling_price: 25 },
    { category: "Tools", name: "double sided tape 1 inch", buying_price: 40, selling_price: 60 },
    { category: "Tools", name: "Sucker", buying_price: 120, selling_price: 170 },
    { category: "Tools", name: "Tip cleaner Copper", buying_price: 170, selling_price: 240 },
    { category: "Tools", name: "soldering flux", buying_price: 70, selling_price: 90 },
    { category: "Tools", name: "Iron Tip", buying_price: 80, selling_price: 100 },
    { category: "Measurements", name: "Multimeter (DT9205)", buying_price: 340, selling_price: 420 },
    { category: "Miscellaneous", name: "Buzzer", buying_price: 10, selling_price: 10 },
    { category: "Miscellaneous", name: "Transparent Acrylic Sheet", buying_price: 150, selling_price: 200 },
    { category: "Miscellaneous", name: "Heat Srink", buying_price: 120, selling_price: 140 },
    { category: "Capacitors", name: "100uF 25V", buying_price: 3, selling_price: 4 },
    { category: "Capacitors", name: "100uF 16V", buying_price: 0, selling_price: 0 },
    { category: "Capacitors", name: "10uF 25V", buying_price: 2, selling_price: 5 },
    { category: "Resistors", name: "1kΩ Resistor", buying_price: 1, selling_price: 2 },
    { category: "Resistors", name: "10kΩ Resistor", buying_price: 1, selling_price: 2 },
    { category: "Resistors", name: "2.2kΩ Resistor", buying_price: 1, selling_price: 2 },
    { category: "Resistors", name: "1mΩ Resistor", buying_price: 1, selling_price: 2 },
    { category: "Resistors", name: "4.7kΩ Resistor", buying_price: 1, selling_price: 2 },
    { category: "Resistors", name: "1.8kΩ Resistor", buying_price: 1, selling_price: 2 },
    { category: "Resistors", name: "220Ω Resistor", buying_price: 1, selling_price: 2 },
    { category: "Resistors", name: "5.6kΩ Resistor", buying_price: 1, selling_price: 2 },
    { category: "Resistors", name: "15kΩ Resistor", buying_price: 1, selling_price: 2 },
    { category: "Resistors", name: "6.8kΩ Resistor", buying_price: 1, selling_price: 2 },
    { category: "Resistors", name: "47kΩ Resistor", buying_price: 1, selling_price: 2 },
    { category: "Resistors", name: "330 Ω Resistor", buying_price: 1, selling_price: 2 },
    { category: "Resistors", name: "1Ω Resistor", buying_price: 1, selling_price: 2 },
    { category: "Resistors", name: "LDR", buying_price: 40, selling_price: 50 },
    { category: "Resistors", name: "1N4007", buying_price: 2, selling_price: 3 },
    { category: "Transistors", name: "BC547 Transistors", buying_price: 2, selling_price: 3 },
    { category: "Battery", name: "18650 pencil cell", buying_price: 60, selling_price: 80 },
    { category: "Battery", name: "2200mAh Llithium Polymer Battery", buying_price: 2100, selling_price: 2400 },
    { category: "Battery", name: "1500mAh 3.7V lithium ion", buying_price: 180, selling_price: 360 },
    { category: "Battery", name: "cell holder 2x", buying_price: 30, selling_price: 40 },
    { category: "Battery", name: "7.4V 900mAh 2s", buying_price: 1000, selling_price: 1120 },
    { category: "Battery", name: "1100mAh 12V LiPo", buying_price: 1150, selling_price: 1150 },
    { category: "Charger", name: "18650 cell holder 3x", buying_price: 40, selling_price: 60 },
    { category: "Charger", name: "5V 2 A Power supply", buying_price: 130, selling_price: 170 },
    { category: "Charger", name: "TMAX B3 Charger", buying_price: 300, selling_price: 390 },
    { category: "Charger", name: "12V 10A Power Supply", buying_price: 550, selling_price: 700 },
    { category: "Charger", name: "3 cell BMS module", buying_price: 60, selling_price: 120 },
    { category: "Charger", name: "10A charger", buying_price: 60, selling_price: 80 },
    { category: "Breadboard", name: "400 tie BreadBoard", buying_price: 60, selling_price: 70 },
    { category: "Breadboard", name: "830 tie BreadBoard", buying_price: 80, selling_price: 100 },
    { category: "Breadboard", name: "170 tie BreadBoard", buying_price: 25, selling_price: 30 },
    { category: "Veroboard", name: "Dot type Veroboard", buying_price: 25, selling_price: 30 },
    { category: "Connector", name: "Male Header Pin", buying_price: 10, selling_price: 15 },
    { category: "Connector", name: "Female Header Pin", buying_price: 10, selling_price: 15 },
    { category: "Connector", name: "XT-60 Connector", buying_price: 25, selling_price: 50 },
    { category: "Connector", name: "JST XH 2 pin Male", buying_price: 5, selling_price: 7.5 },
    { category: "Connector", name: "JST XH 2 pin Female", buying_price: 5, selling_price: 7.5 },
    { category: "Connector", name: "JST XH 3 pin Male", buying_price: 5, selling_price: 7.5 },
    { category: "Connector", name: "JST XH 3 pin Female", buying_price: 5, selling_price: 7.5 },
    { category: "Connector", name: "JST XH 4 pin Male", buying_price: 7.5, selling_price: 12.5 },
    { category: "Connector", name: "JST XH 4 pin Female", buying_price: 7.5, selling_price: 12.5 },
    { category: "Connector", name: "JST XH 5 pin Male", buying_price: 10, selling_price: 15 },
    { category: "Connector", name: "JST XH 5 pin Female", buying_price: 10, selling_price: 15 },
    { category: "Connector", name: "JST XH 6 pin Male", buying_price: 10, selling_price: 15 },
    { category: "Connector", name: "JST XH 6 pin Female", buying_price: 10, selling_price: 15 },
    { category: "Connector", name: "JST XH 10 pin Male", buying_price: 15, selling_price: 22.5 },
    { category: "Connector", name: "JST XH 10 pin Female", buying_price: 15, selling_price: 22.5 },
    { category: "Relay", name: "1 Channel Relay 5V", buying_price: 50, selling_price: 80 }
];
